name : CI

on:
    push: dev

jobs:
    login:  
        runs-on: ubuntu-latest
        steps:
            
            - name: login to dockerhub
              uses: docker/login-action@v3
              with:
                username : ${{ secrets.DOCKERHUB_USERNAME }}
                password:  ${{ secrets.DOCKERHUB_TOKEN }}

